import { useEffect, useRef, useState, type ReactNode } from "react";
import { ActivityIndicator, BackHandler, StyleSheet, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { File,Paths } from "expo-file-system";
import { api } from "./api";
import type { LearningConcept, LearningUnit, PaidSetupState } from "./types";
import { Brand, C, Chip, Field, Notice, PrimaryButton, Screen } from "./ui";
import { Pressable } from "./PointerPressable";

type Phase="intro"|"context"|"review"|"customize"|"confirm"|"generating"|"failed"|"ready";
const productStyles=["B2B SaaS","Fintech","E-commerce","Developer tools"];

export function LayerThree({token,onHome,onLearn}:{token:string;onHome:()=>void;onLearn:()=>void}){
  const [state,setState]=useState<PaidSetupState|null>(null);
  const [phase,setPhase]=useState<Phase>("intro");
  const [busy,setBusy]=useState(true);const [error,setError]=useState("");
  const generationStarted=useRef(false);

  useEffect(()=>{api.startPaidSetup(token).then(next=>{setState(next);setPhase(phaseFor(next.status));}).catch(e=>setError(message(e))).finally(()=>setBusy(false));},[token]);
  useEffect(()=>{
    if(!state||state.status!=="TRIAL_GENERATING")return;
    const timer=setInterval(()=>{api.paidSetup(token).then(next=>{setState(next);setPhase(phaseFor(next.status));}).catch(()=>undefined);},2000);
    return()=>clearInterval(timer);
  },[state?.status,token]);
  useEffect(()=>{
    if(!state||state.status!=="TRIAL_SCOPE_CONFIRMED"||generationStarted.current)return;
    generationStarted.current=true;
    setPhase("generating");setBusy(true);
    api.generateLearningUnits(token,state).then(next=>{setState(next);setPhase(phaseFor(next.status));}).catch(async e=>{setError(message(e));try{const latest=await api.paidSetup(token);setState(latest);setPhase(phaseFor(latest.status));if(latest.status==="TRIAL_GENERATION_FAILED")generationStarted.current=false;}catch{setPhase("failed");}}).finally(()=>setBusy(false));
  },[state?.status,token]);
  function back(){if(phase==="context")setPhase("intro");else if(phase==="customize")setPhase("review");else if(phase==="confirm")setPhase("customize");else onHome();}
  useEffect(()=>{const listener=BackHandler.addEventListener("hardwareBackPress",()=>{back();return true;});return()=>listener.remove();},[phase]);

  if(busy&&!state)return <LayerShell onBack={onHome}><View style={s.center}><ActivityIndicator color={C.blue} size="large"/><Text style={s.muted}>Loading your saved setup…</Text></View></LayerShell>;
  if(!state)return <LayerShell onBack={onHome}><Notice tone="red">{error||"Your learning setup could not be loaded."}</Notice><PrimaryButton label="Back to Home" onPress={onHome}/></LayerShell>;
  const common={state,setState,setPhase,setBusy,busy,error,setError,onHome,onLearn,back,token};
  if(phase==="intro")return <Intro {...common}/>;
  if(phase==="context")return <Context {...common}/>;
  if(phase==="review")return <Review {...common}/>;
  if(phase==="customize")return <Customize {...common}/>;
  if(phase==="confirm")return <Confirm {...common}/>;
  if(phase==="generating")return <Generating {...common}/>;
  if(phase==="failed")return <Failed {...common}/>;
  return <Ready {...common}/>;
}

type Common={token:string;state:PaidSetupState;setState:(s:PaidSetupState)=>void;setPhase:(p:Phase)=>void;busy:boolean;setBusy:(b:boolean)=>void;error:string;setError:(e:string)=>void;onHome:()=>void;onLearn:()=>void;back:()=>void};
function phaseFor(status:PaidSetupState["status"]):Phase{return status==="TRIAL_PAID_SETUP_PENDING"?"intro":status==="TRIAL_SCOPE_PROPOSED"?"review":status==="TRIAL_GENERATION_FAILED"?"failed":status==="TRIAL_READY"?"ready":"generating";}

function Intro({setPhase,onHome}:Common){return <LayerShell onBack={onHome}><Text style={s.h1}>Shape your personalized learning trial</Text><Text style={s.subtitle}>Confirm a few details, review your learning scope, and generate exactly two focused learning units.</Text><View style={s.hero}><Text style={s.heroIcon}>◎</Text><Text style={s.heroTitle}>Your learning path starts here</Text></View><Card><Text style={s.cardTitle}>Two focused learning units</Text><Text style={s.copy}>Your units will be generated from your goal, current skills, interests, timeline and optional target context.</Text><Step number="1" title="Unit 1" detail="Focused on your confirmed scope"/><Step number="2" title="Unit 2" detail="Builds coherently on your first unit"/></Card><PrimaryButton label="Continue setup" onPress={()=>setPhase("context")}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Context(props:Common){const{state,token,setState,setPhase,setBusy,busy,setError,error,onHome,back}=props;const[jd,setJd]=useState(state.context.jdText||"");const[jdFilename,setJdFilename]=useState("");const[company,setCompany]=useState(state.context.targetCompany||"");const[styles,setStyles]=useState((state.context.productStyle||"").split(",").map(x=>x.trim()).filter(Boolean));const[depth,setDepth]=useState<"BASIC"|"STANDARD"|"DEEP">(state.context.targetDepth||"STANDARD");
  async function pickJd(){setError("");const result=await DocumentPicker.getDocumentAsync({type:Object.values(documentMimeTypes),copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];if(!asset)return;if((asset.size||0)>2*1024*1024)return setError("Choose a job description smaller than 2 MB.");const mimeType=documentMimeType(asset.name,asset.mimeType);if(!mimeType)return setError("Choose a PDF, DOCX or TXT job description.");const uriScheme=asset.uri.split(":",1)[0]||"unknown";console.info("[jd] file selected",{filename:asset.name,mimeType,size:asset.size??null,uriScheme});setBusy(true);let cached:File|null=null;try{let readable=new File(asset.uri);if(uriScheme==="content"){cached=new File(Paths.cache,`jd-${Date.now()}${documentExtension(asset.name,mimeType)}`);await readable.copy(cached,{overwrite:true});readable=cached;}const contentBase64=await readable.base64();console.info("[jd] file bytes read",{filename:asset.name,mimeType,size:asset.size??null,uriScheme,bytesRead:contentBase64.length>0});const parsed=await api.readJdDocument(token,{filename:asset.name,mimeType,contentBase64});setJd(parsed.text);setJdFilename(parsed.filename);console.info("[jd] extraction completed",{filename:asset.name,textRead:parsed.text.length>0});}catch(e){console.error("[jd] extraction failed",{filename:asset.name,mimeType,size:asset.size??null,uriScheme,error:message(e)});setError(message(e));}finally{if(cached?.exists)cached.delete();setBusy(false);}}
  async function next(context={jdText:jd.trim()||null,targetCompany:company.trim()||null,productStyle:styles.join(", ")||null,targetDepth:depth}){setBusy(true);setError("");try{const saved=await api.savePaidContext(token,state,context);const proposed=await api.proposeLearningScope(token,saved);setState(proposed);setPhase("review");}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <LayerShell onBack={back} step="Step 5 of 7"><Text style={s.h1}>Add optional target context</Text><Text style={s.subtitle}>A job description, target company or product style helps tailor examples and projects.</Text><Card><Text style={s.cardTitle}>Target depth</Text><Text style={s.copy}>Choose how far the complete learning path should take you.</Text><View style={s.wrap}>{(["BASIC","STANDARD","DEEP"] as const).map(item=><Chip key={item} label={item[0]+item.slice(1).toLowerCase()} selected={depth===item} onPress={()=>setDepth(item)}/>)}</View></Card><Card><Text style={s.cardTitle}>Job description</Text><Field label="Optional role brief" value={jd} onChangeText={setJd} multiline placeholder="Paste a job description here…"/><Secondary label={jdFilename?`Replace ${jdFilename}`:"Upload PDF, DOCX or TXT"} onPress={()=>void pickJd()} disabled={busy}/>{jdFilename?<Text style={s.copy}>Text loaded from {jdFilename}. You can review or edit it above.</Text>:null}</Card><Card><Text style={s.cardTitle}>Target company</Text><Field label="Optional company" value={company} onChangeText={setCompany} placeholder="Enter a company name"/></Card><Card><Text style={s.cardTitle}>Product style</Text><Text style={s.copy}>Select any that apply.</Text><View style={s.wrap}>{productStyles.map(item=><Chip key={item} label={item} selected={styles.includes(item)} onPress={()=>setStyles(toggle(styles,item))}/>)}</View></Card>{error?<Notice tone="red">{error}</Notice>:null}<PrimaryButton label={busy?"Working…":"Continue"} onPress={()=>void next()} busy={busy}/><Secondary label="Skip optional context" onPress={()=>void next({jdText:null,targetCompany:null,productStyle:null,targetDepth:depth})} disabled={busy}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Review({state,setPhase,onHome,back}:Common){return <LayerShell onBack={back} step="Step 6 of 7"><Text style={s.h1}>Review your proposed learning map</Text><Text style={s.subtitle}>This map was generated from your goal, current profile and optional target context.</Text>{state.learningMap.map(cap=><Capability key={cap.capabilityId} capability={cap}/>) }<Notice>ⓘ Exactly two learning units will be generated after confirmation.</Notice><PrimaryButton label="Customize concepts" onPress={()=>setPhase("customize")}/><Secondary label="Looks good" onPress={()=>setPhase("confirm")}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Customize({state,token,setState,setPhase,setBusy,busy,setError,error,onHome,back}:Common){const concepts=state.learningMap.flatMap(cap=>cap.concepts);const[selected,setSelected]=useState(new Set(concepts.filter(c=>c.selected).map(c=>c.conceptId)));const known=concepts.filter(c=>c.status==="KNOWN"),recommended=concepts.filter(c=>c.status==="RECOMMENDED"),deep=concepts.filter(c=>c.status==="DEEP");
  async function save(){setBusy(true);setError("");try{const editable=concepts.filter(c=>c.status!=="KNOWN").map(c=>({conceptId:c.conceptId,selected:selected.has(c.conceptId)}));let next=state;for(const item of editable){const current=next.learningMap.flatMap(x=>x.concepts).find(c=>c.conceptId===item.conceptId);if(current?.selected!==item.selected)next=await api.saveLearningScope(token,next,[item]);}setState(next);setPhase("confirm");}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <LayerShell onBack={back} step="Step 6 of 7"><Text style={s.h1}>Customize your concepts</Text><Text style={s.subtitle}>Known concepts stay visible for context. Choose the concepts you want included.</Text><ConceptGroup title={`Known concepts (${known.length})`} concepts={known} selected={selected} locked onToggle={()=>undefined}/><ConceptGroup title="Recommended to learn" concepts={recommended} selected={selected} onToggle={id=>setSelected(changeSet(selected,id))}/><ConceptGroup title="Optional deeper concepts" concepts={deep} selected={selected} onToggle={id=>setSelected(changeSet(selected,id))}/>{error?<Notice tone="red">{error}</Notice>:null}<PrimaryButton label="Review scope" onPress={()=>void save()} busy={busy}/><Secondary label="Back" onPress={back}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Confirm({state,token,setState,setPhase,setBusy,busy,setError,error,onHome,back}:Common){const selected=state.learningMap.flatMap(cap=>cap.concepts).filter(c=>c.selected);const known=state.learningMap.flatMap(cap=>cap.concepts).filter(c=>c.status==="KNOWN");
  async function generate(){setBusy(true);setError("");try{const confirmed=await api.confirmLearningScope(token,state);setState(confirmed);setPhase("generating");}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <LayerShell onBack={back} step="Step 6 of 7"><Text style={s.h1}>Confirm your learning scope</Text><Text style={s.subtitle}>Review your final selection before generating your first two learning units.</Text><Card><Text style={s.cardTitle}>Selected concepts ({selected.length})</Text><View style={s.wrap}>{selected.map(c=><Pill key={c.conceptId} text={c.name}/>)}</View></Card><Card><Text style={s.cardTitle}>Dependencies checked</Text><Text style={s.copy}>Required prerequisites are included or already represented in your profile.</Text></Card>{known.length?<Card><Text style={s.cardTitle}>Known concepts ({known.length})</Text><Text style={s.copy}>Visible for context and excluded from reteaching.</Text><View style={s.wrap}>{known.map(c=><Pill key={c.conceptId} text={c.name}/>)}</View></Card>:null}<Card><Text style={s.cardTitle}>Target context</Text><Text style={s.copy}>{[state.context.targetCompany,state.context.productStyle].filter(Boolean).join(" · ")||"No optional target context added"}</Text></Card>{error?<Notice tone="red">{error}</Notice>:null}<PrimaryButton label="Confirm learning scope" onPress={()=>void generate()} busy={busy}/><Secondary label="Back" onPress={back}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Generating({onHome}:Common){return <LayerShell onBack={onHome} step="Step 7 of 7"><View style={s.center}><ActivityIndicator size="large" color={C.blue}/><Text style={s.h1}>Generating your first 2 learning units…</Text><Text style={s.subtitle}>We’re preparing a personalized learning path from your confirmed scope.</Text></View><Card><Step number="✓" title="Checking selections and dependencies" detail="Validating your confirmed concepts"/><Step number="●" title="Preparing your learning path" detail="Organizing concepts into a coherent sequence"/><Step number="○" title="Creating two focused units" detail="Personalizing goals, context and future lab outcomes"/></Card><Notice>✓ Your confirmed scope is saved. You can safely return Home while generation completes.</Notice><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Failed({state,token,setState,setPhase,setBusy,busy,setError,error,onHome}:Common){async function retry(){setBusy(true);setError("");setPhase("generating");try{const ready=await api.generateLearningUnits(token,state);setState(ready);setPhase(phaseFor(ready.status));}catch(e){setError(message(e));try{const latest=await api.paidSetup(token);setState(latest);setPhase(phaseFor(latest.status));}catch{setPhase("failed");}}finally{setBusy(false);}}return <LayerShell onBack={onHome}><View style={s.center}><Text style={s.failIcon}>!</Text><Text style={s.h1}>We couldn’t generate your units</Text><Text style={s.subtitle}>Your confirmed scope is saved. You can retry without losing your selections.</Text></View><Notice tone="red">{error||"Generation was interrupted. Please try again."}</Notice><Card><Text style={s.cardTitle}>Your scope is safe</Text><Text style={s.copy}>Your focus areas, selected concepts and target context will be reused.</Text></Card><PrimaryButton label="Retry generation" onPress={()=>void retry()} busy={busy}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function Ready({state,onHome,onLearn}:Common){return <LayerShell onBack={onHome}><Notice tone="green">✓ 2 learning units created</Notice><Text style={s.h1}>Your trial path is ready</Text><Text style={s.subtitle}>Your two generated units are ready and will also appear on Home.</Text>{state.units.map(unit=><UnitCard key={unit.unitId} unit={unit}/>) }<PrimaryButton label="Continue to learning" onPress={onLearn}/><Secondary label="Back to Home" onPress={onHome}/></LayerShell>}

function LayerShell({children,onBack,step}:{children:ReactNode;onBack:()=>void;step?:string}){return <View style={s.root}><Screen><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack} style={s.back}><Text style={s.backText}>←</Text></Pressable><Brand compact/><View style={{width:36}}/></View>{step?<Text style={s.stepLabel}>{step}</Text>:null}{children}</Screen><View style={s.tabs}><Tab icon="⌂" label="Home"/><Tab icon="▤" label="Learn" active/><Tab icon="▣" label="My Work"/><Tab icon="♙" label="You"/></View></View>}
function Card({children}: {children:ReactNode}){return <View style={s.card}>{children}</View>}
function Step({number,title,detail}:{number:string;title:string;detail:string}){return <View style={s.step}><View style={s.stepNumber}><Text style={s.stepNumberText}>{number}</Text></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.copy}>{detail}</Text></View></View>}
function Capability({capability}:{capability:PaidSetupState["learningMap"][number]}){return <Card><Text style={s.cardTitle}>{capability.name}</Text><Text style={s.copy}>{capability.reason}</Text><Text style={s.scenario}>{capability.scenario}</Text><View style={s.wrap}>{capability.concepts.map(c=><Pill key={c.conceptId} text={c.name}/>)}</View></Card>}
function ConceptGroup({title,concepts,selected,locked=false,onToggle}:{title:string;concepts:LearningConcept[];selected:Set<string>;locked?:boolean;onToggle:(id:string)=>void}){if(!concepts.length)return null;return <Card><Text style={s.cardTitle}>{title}</Text>{concepts.map(c=><Pressable disabled={locked} key={c.conceptId} onPress={()=>onToggle(c.conceptId)} style={[s.concept,selected.has(c.conceptId)&&s.conceptOn]}><Text style={s.checkbox}>{locked?"▣":selected.has(c.conceptId)?"✓":"○"}</Text><View style={{flex:1}}><Text style={s.rowTitle}>{c.name}</Text><Text style={s.copy}>{c.recommendationReason}</Text></View></Pressable>)}</Card>}
function UnitCard({unit}:{unit:LearningUnit}){return <Card><Text style={s.cardTitle}>Unit {unit.sequence}: {unit.title}</Text><Text style={s.unitGoal}>{unit.goal}</Text><Text style={s.metaTitle}>Included concepts</Text><View style={s.wrap}>{unit.concepts.map(c=><Pill key={c.conceptId} text={c.name}/>)}</View><Text style={s.metaTitle}>Prerequisites</Text><Text style={s.copy}>{unit.prerequisites.join(", ")||"No additional prerequisites"}</Text><Text style={s.metaTitle}>Product context</Text><Text style={s.copy}>{unit.productContext}</Text><Text style={s.metaTitle}>Future lab outcome</Text><Text style={s.copy}>{unit.labOutcomePlaceholder}</Text></Card>}
function Pill({text}:{text:string}){return <Text style={s.pill}>{text}</Text>}
function Secondary({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.secondary,disabled&&{opacity:.5}]}><Text style={s.secondaryText}>{label}</Text></Pressable>}
function Tab({icon,label,active=false}:{icon:string;label:string;active?:boolean}){return <View style={s.tab}><Text style={[s.tabIcon,active&&{color:C.blue}]}>{icon}</Text><Text style={[s.tabLabel,active&&{color:C.blue,fontWeight:"800"}]}>{label}</Text></View>}
function toggle(values:string[],item:string){return values.includes(item)?values.filter(x=>x!==item):[...values,item]}
function changeSet(values:Set<string>,item:string){const next=new Set(values);if(next.has(item))next.delete(item);else next.add(item);return next}
function message(error:unknown){return error instanceof Error?error.message:"Something went wrong. Please try again."}
const documentMimeTypes={".pdf":"application/pdf",".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",".txt":"text/plain"} as const;
function documentMimeType(filename:string,reported?:string|null){const lower=filename.toLowerCase();const extension=(Object.keys(documentMimeTypes) as (keyof typeof documentMimeTypes)[]).find(x=>lower.endsWith(x));if(extension)return documentMimeTypes[extension];return (Object.values(documentMimeTypes) as string[]).includes(reported||"")?reported!:null;}
function documentExtension(filename:string,mimeType:string){const extension=Object.keys(documentMimeTypes).find(x=>filename.toLowerCase().endsWith(x));return extension??(mimeType==="application/pdf"?".pdf":mimeType==="text/plain"?".txt":".docx");}

const s=StyleSheet.create({root:{flex:1,backgroundColor:"white"},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:8},back:{width:36,height:36,borderRadius:10,backgroundColor:"#F3F6FA",alignItems:"center",justifyContent:"center"},backText:{color:C.ink,fontSize:22,fontWeight:"800"},stepLabel:{color:C.muted,fontSize:12,fontWeight:"700",marginBottom:8},h1:{color:C.ink,fontSize:27,lineHeight:32,fontWeight:"900",marginTop:8},subtitle:{color:C.muted,fontSize:14,lineHeight:20,marginTop:6,marginBottom:18},hero:{minHeight:155,borderRadius:18,backgroundColor:"#F0F7FF",alignItems:"center",justifyContent:"center",marginBottom:14},heroIcon:{color:C.blue,fontSize:44,fontWeight:"900"},heroTitle:{color:C.ink,fontWeight:"900",fontSize:18,marginTop:8},card:{borderWidth:1,borderColor:C.line,borderRadius:15,padding:14,backgroundColor:"white",marginBottom:12},cardTitle:{color:C.ink,fontSize:16,fontWeight:"900",marginBottom:6},copy:{color:C.muted,fontSize:12,lineHeight:17,marginTop:2},scenario:{color:C.blue,fontSize:12,lineHeight:17,backgroundColor:"#F2F7FF",padding:9,borderRadius:9,marginVertical:9},step:{flexDirection:"row",alignItems:"center",marginTop:12},stepNumber:{width:32,height:32,borderRadius:16,backgroundColor:"#E4EEFF",alignItems:"center",justifyContent:"center",marginRight:10},stepNumberText:{color:C.blue,fontWeight:"900"},rowTitle:{color:C.ink,fontSize:13,fontWeight:"800"},wrap:{flexDirection:"row",flexWrap:"wrap",marginTop:8},pill:{color:"#087C55",backgroundColor:"#E1F7ED",borderRadius:8,paddingHorizontal:9,paddingVertical:6,fontSize:11,fontWeight:"700",marginRight:6,marginBottom:6},concept:{flexDirection:"row",borderWidth:1,borderColor:C.line,borderRadius:11,padding:11,marginTop:8,backgroundColor:"white"},conceptOn:{borderColor:"#A9C9FF",backgroundColor:"#F1F6FF"},checkbox:{color:C.blue,fontWeight:"900",fontSize:17,width:27},secondary:{borderWidth:1,borderColor:"#A9C9FF",borderRadius:11,minHeight:46,alignItems:"center",justifyContent:"center",marginTop:9},secondaryText:{color:C.blue,fontWeight:"800",fontSize:13},center:{alignItems:"center",justifyContent:"center",paddingVertical:36},muted:{color:C.muted,marginTop:12},failIcon:{width:62,height:62,borderRadius:31,backgroundColor:"#FFE8E8",color:C.red,fontSize:40,textAlign:"center",lineHeight:62,fontWeight:"900"},unitGoal:{color:C.ink,fontSize:13,lineHeight:18,marginBottom:8},metaTitle:{color:C.ink,fontSize:12,fontWeight:"900",marginTop:9},tabs:{height:68,borderTopWidth:1,borderTopColor:"#E8EDF4",backgroundColor:"white",flexDirection:"row",paddingBottom:5},tab:{flex:1,alignItems:"center",justifyContent:"center"},tabIcon:{color:C.muted,fontSize:22},tabLabel:{color:C.muted,fontSize:10,marginTop:3}});
