import type { BillingState,ContinuationState,OnboardingState } from "@adaptive-labs/contracts";
import { useEffect,useState,type FormEvent,type InputHTMLAttributes,type ReactNode } from "react";
import { Link } from "react-router-dom";
import { api,ApiError } from "./api";
import { useAuth } from "./auth";
import { accessTypeLabel,continuationView } from "./access-model";

function authenticated(){const auth=useAuth();if(auth.status!=="authenticated")throw new Error("Authenticated page rendered without a session");return auth;}

export function ProfilePage(){const auth=authenticated();const source=auth.onboarding;const [name,setName]=useState(source.profile.displayName??"");const [role,setRole]=useState(source.profile.currentRole??"");const [experience,setExperience]=useState(source.profile.experienceYears?.toString()??"");const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const [error,setError]=useState("");
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setStatus("");setError("");try{await api.profile(auth.token,source,{displayName:name.trim(),currentRole:role.trim(),experienceYears:experience===""?null:Number(experience)});setStatus("Profile saved to your shared learner record.");await auth.refresh();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
  return <Page title="You" detail="Profile details and learning context from the same learner record used on mobile."><form className="account-form" onSubmit={save}><div className="form-grid"><Field label="Display name" value={name} onChange={setName}/><Field label="Current role" value={role} onChange={setRole}/><Field label="Years of experience" value={experience} onChange={setExperience} type="number" min="0" max="80"/></div>{error?<Alert tone="error">{error}{isConflict(error)?<><br/><button type="button" className="text-button inline" onClick={()=>void auth.refresh()}>Reload latest profile</button></>:null}</Alert>:null}{status?<Alert>{status}</Alert>:null}<button className="primary-button account-save" disabled={busy}>{busy?"Saving…":"Save profile"}</button></form><section className="account-section"><h2>Learning direction</h2><Data label="Goal" value={source.goal?.target??"Not set"}/><Data label="Skills" value={source.skills.length?source.skills.map(skill=>skill.name).join(", "):"Not set"}/><Data label="Interests" value={source.interests.length?source.interests.join(", "):"Not set"}/><p className="section-note">Goal, resume, and skill-scope changes stay in the existing setup flow so they remain consistent with your generated learning path.</p>{!source.completed?<Link className="secondary-link" to="/onboarding">Continue learner setup</Link>:null}</section></Page>;
}
export function SettingsPage(){const auth=authenticated();const source=auth.onboarding;const [days,setDays]=useState(source.preferences.timelineDays?.toString()??"");const [pace,setPace]=useState<NonNullable<OnboardingState["preferences"]["pace"]>>(source.preferences.pace??"STEADY");const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const [error,setError]=useState("");
 async function save(event:FormEvent){event.preventDefault();const value=Number(days);if(!Number.isInteger(value)||value<1||value>3650){setError("Timeline must be between 1 and 3650 days.");return;}setBusy(true);setError("");setStatus("");try{await api.preferences(auth.token,source,value,pace);setStatus("Learning preferences saved.");await auth.refresh();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 return <Page title="Settings" detail="Only preferences and session controls already supported by AdaptiveSkills are shown here."><form className="account-form" onSubmit={save}><div className="form-grid"><Field label="Learning timeline (days)" value={days} onChange={setDays} type="number" min="1" max="3650"/><label className="field"><span>Learning pace</span><select value={pace} onChange={event=>setPace(event.target.value as typeof pace)}><option value="CASUAL">Casual</option><option value="STEADY">Steady</option><option value="INTENSIVE">Intensive</option></select></label></div>{error?<Alert tone="error">{error}</Alert>:null}{status?<Alert>{status}</Alert>:null}<button className="primary-button account-save" disabled={busy}>{busy?"Saving…":"Save preferences"}</button></form><section className="account-section danger-lite"><h2>Session</h2><p>Sign out of this browser. Your backend-owned learning progress remains saved.</p><button className="secondary-button" onClick={()=>void auth.signOut()}>Sign out</button></section></Page>;
}

export function BillingPage(){const auth=authenticated();const [billing,setBilling]=useState<BillingState|null>(null);const [continuation,setContinuation]=useState<ContinuationState|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");const results=await Promise.allSettled([api.billing(auth.token),api.continuation(auth.token)]);if(results[0].status==="fulfilled")setBilling(results[0].value);else setError(errorMessage(results[0].reason));if(results[1].status==="fulfilled")setContinuation(results[1].value);setLoading(false);}
 useEffect(()=>{void load();},[auth.token]);
 async function perform(name:string,work:()=>Promise<unknown>){setBusy(name);setError("");try{await work();await auth.refresh();await load();}catch(reason){setError(errorMessage(reason));}finally{setBusy("");}}
 if(loading)return <Page title="Billing & access" detail="Checking verified entitlement and runway state…"><div className="billing-loading"><span className="spinner" role="status" aria-label="Loading access status"/></div></Page>;
 return <Page title="Billing & access" detail="Access is verified by the AdaptiveSkills backend from RevenueCat records.">{error?<Alert tone="error">{error}</Alert>:null}{billing?<><div className="entitlement-grid"><Entitlement title="Initial TRY_IT access" item={billing.access.initialEntitlement}/><Entitlement title="Continuation access" item={billing.access.continuationEntitlement}/></div><section className="access-summary"><span className="eyebrow">CURRENT ACCESS</span><h2>{accessTypeLabel(billing.access.type)}</h2><p>Trial status: {human(billing.trialStatus)}. {billing.message}</p></section></>:null}{continuation?<ContinuationCard value={continuation} busy={busy} onAnalyze={()=>perform("analyze",()=>api.analyzeContinuation(auth.token))} onVerify={()=>perform("growth",()=>api.reconcileContinuationAccess(auth.token))}/>:null}<section className="restore-card"><h2>Restore or refresh access</h2><p>If you purchased TRY_IT in the AdaptiveSkills mobile app, ask the backend to reconcile RevenueCat and reload this page.</p><button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void perform("initial",()=>api.reconcileInitialAccess(auth.token))}>{busy==="initial"?"Checking…":"Refresh initial access"}</button></section></Page>;
}
function ContinuationCard({value,busy,onAnalyze,onVerify}:{value:ContinuationState;busy:string;onAnalyze:()=>void;onVerify:()=>void}){const view=continuationView(value.status);return <section className="continuation-card"><span className="eyebrow">NEXT RUNWAY</span><h2>{human(value.status)}</h2><p>{value.nextOffer?`${value.nextOffer.plannedUnits} units and ${value.nextOffer.plannedLabs} labs are proposed.`:"Your backend-owned continuation state is shown here."}</p>{view==="ANALYZE"?<button className="primary-button account-save" disabled={Boolean(busy)} onClick={onAnalyze}>{busy==="analyze"?"Preparing proposal…":"Prepare next runway"}</button>:null}{view==="PURCHASE_REQUIRED"?<><Alert>Your runway proposal is preserved. Purchase it through the AdaptiveSkills mobile app, where RevenueCat supplies the localized price and purchase sheet. Web does not simulate or activate purchases.</Alert><button className="primary-button account-save" disabled={Boolean(busy)||!value.nextOffer?.available} onClick={onVerify}>{busy==="growth"?"Verifying…":"I purchased on mobile — verify access"}</button>{!value.nextOffer?.available?<p className="field-help">The configured continuation package is currently unavailable.</p>:null}</>:null}{view==="VERIFYING"?<Alert>Purchase is verified and the backend is preparing your first next unit. Refresh Home when preparation completes.</Alert>:null}{view==="ACTIVE"?<Alert>Continuation access is active. <Link to="/home">Return Home</Link> to continue learning.</Alert>:null}</section>;}
function Entitlement({title,item}:{title:string;item:BillingState["access"]["initialEntitlement"]}){return <article className="entitlement-card"><div><span className="eyebrow">{title}</span><strong className={`entitlement-status ${item.status.toLowerCase()}`}>{human(item.status)}</strong></div><p>{item.productId?`Product: ${item.productId}`:"No verified product is recorded."}</p>{item.purchasedAt?<time dateTime={item.purchasedAt}>Recorded {new Date(item.purchasedAt).toLocaleDateString()}</time>:null}</article>;}

export function HelpPage(){return <Page title="Help & Support" detail="A guide to the existing AdaptiveSkills learning flow and common recovery steps."><div className="help-grid"><Help title="How learning progresses">Home always follows the next action prepared by the backend. Complete each concept section, finish the unit, then open its practical lab. Your exact position is shared across web and mobile.</Help><Help title="Labs, hints, and System Assistance">YOU BUILD files autosave while you type. Run checks before submitting. Hints are file-specific. System Assistance can unblock you, but assisted work is recorded separately from independent evidence.</Help><Help title="Notes, marked words, and doubts">Select teaching text to save a note, mark terminology, or record a doubt. Saved Notes and Marked Words remain available from the sidebar. Doubts are handled by the existing checkpoints and future adaptation rules.</Help><Help title="Access and continuation">TRY_IT and continuation are separate RevenueCat entitlements. Purchases use the mobile RevenueCat flow; Billing on web displays and reconciles verified backend state.</Help><Help title="Reload or network problems">Check your connection, then retry the page. If a save reports a version conflict, reload the latest record before editing again. Lab drafts show their save state beside the editor.</Help><Help title="Session problems">If your session expires, sign in again with the same account. Signing out does not delete progress. Persistent failures should be checked against the deployed API health and logs by the project operator.</Help></div></Page>;}

function Page({title,detail,children}:{title:string;detail:string;children:ReactNode}){return <section className="page-card final-page"><span className="eyebrow">ADAPTIVESKILLS</span><h1>{title}</h1><p className="page-detail">{detail}</p>{children}</section>;}
function Field({label,value,onChange,...props}:{label:string;value:string;onChange:(value:string)=>void}&Omit<InputHTMLAttributes<HTMLInputElement>,"value"|"onChange">){return <label className="field"><span>{label}</span><input {...props} value={value} onChange={event=>onChange(event.target.value)}/></label>;}
function Data({label,value}:{label:string;value:string}){return <div className="account-data"><span>{label}</span><strong>{value}</strong></div>;}
function Alert({children,tone="info"}:{children:ReactNode;tone?:"info"|"error"}){return <div className={`notice ${tone}`} role={tone==="error"?"alert":"status"}>{children}</div>;}
function Help({title,children}:{title:string;children:ReactNode}){return <article><h2>{title}</h2><p>{children}</p></article>;}
function human(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^./,letter=>letter.toUpperCase());}
function errorMessage(reason:unknown){if(reason instanceof ApiError&&reason.code==="PURCHASE_NOT_VERIFIED")return"RevenueCat has not verified continuation access yet. Access remains locked.";return reason instanceof Error?reason.message:"Something went wrong. Try again.";}
function isConflict(value:string){return /reload|version|changed/i.test(value);}
