import { createHash } from "node:crypto";
import { z } from "zod";

const key=z.string().regex(/^[a-z0-9][a-z0-9-]{1,79}$/);
const requirement=z.strictObject({name:z.string().min(1).max(160),classification:z.enum(["REQUIRED","USEFUL","OPTIONAL"]),reason:z.string().min(1).max(500),source:z.enum(["GOAL","PROFILE","JD","INTEREST"])});
const contextualReason=z.string().trim().min(12).max(500).refine(value=>!["Matches a learner-confirmed skill","Recommended by the reasoning engine"].includes(value),"A contextual learner-specific explanation is required");
const concept=z.strictObject({
  key,name:z.string().min(1).max(120),shortExample:z.string().min(1).max(300),
  relationship:z.enum(["KNOWN_REPORTED","RECOMMENDED_NEXT","DEEPER_OPTIONAL","NOT_RELEVANT"]),
  recommendationReason:contextualReason,selected:z.boolean(),depthCategory:z.enum(["FOUNDATION","APPLIED","DEEP"]),
  requirementClass:z.enum(["REQUIRED","USEFUL","OPTIONAL"]),aliases:z.array(z.string().min(1).max(100)).max(15),prerequisites:z.array(key).max(15),
});
const capability=z.strictObject({key,name:z.string().min(1).max(120),tab:z.string().min(1).max(100),reason:z.string().min(1).max(500),scenario:z.string().min(1).max(500),concepts:z.array(concept).min(1).max(20)});
export const proposalSchema=z.strictObject({
  targetPath:z.enum(["FRONTEND_ENGINEER","BACKEND_ENGINEER","FULL_STACK_ENGINEER","AI_APPLICATION_ENGINEER","CLOUD_DEVOPS_ENGINEER"]),
  requirements:z.array(requirement).min(1).max(30),capabilities:z.array(capability).min(2).max(6),
}).superRefine((value,ctx)=>{
  const keys=value.capabilities.flatMap(x=>x.concepts.map(c=>c.key));
  if(new Set(keys).size!==keys.length) ctx.addIssue({code:"custom",message:"Concept keys must be unique",params:{reason:"DUPLICATE_CONCEPT_KEY"}});
  const known=new Set(keys);for(const [capabilityIndex,capability] of value.capabilities.entries())for(const [conceptIndex,c] of capability.concepts.entries())for(const [prerequisiteIndex,dependency] of c.prerequisites.entries())
    if(!known.has(dependency)) ctx.addIssue({code:"custom",path:["capabilities",capabilityIndex,"concepts",conceptIndex,"prerequisites",prerequisiteIndex],message:"Prerequisite must reference a concept in this proposal",params:{reason:"UNKNOWN_PREREQUISITE"}});
});
const unit=z.strictObject({sequence:z.union([z.literal(1),z.literal(2)]),title:z.string().min(1).max(160),goal:z.string().min(1).max(500),conceptKeys:z.array(key).min(1),prerequisiteNames:z.array(z.string().min(1).max(120)).max(20),productContext:z.string().min(1).max(500),groupingReason:z.string().min(1).max(500),futureLabOutcome:z.string().min(1).max(500)});
export const unitsPlanSchema=z.strictObject({units:z.array(unit).length(2)}).refine(x=>x.units[0]?.sequence===1&&x.units[1]?.sequence===2,"Units must be ordered 1, 2");
export type Proposal=z.infer<typeof proposalSchema>;export type UnitsPlan=z.infer<typeof unitsPlanSchema>;
export type LearnerReasoningInput={learnerId:string;goal:string;role:string|null;experienceYears:number|null;skills:{name:string;canonicalName:string;level:string|null;source:string}[];interests:string[];timelineDays:number|null;pace:string|null;jdText:string|null;targetCompany:string|null;productStyle:string|null;targetDepth?:"BASIC"|"STANDARD"|"DEEP"};
export type ConfirmedScopeInput=LearnerReasoningInput&{targetPath:Proposal["targetPath"];capabilities:{name:string;reason:string;scenario:string;concepts:{key:string;name:string;shortExample:string;depthCategory:string;requirementClass:string;prerequisites:string[]}[]}[]};
const resumeSkillsSchema=z.strictObject({skills:z.array(z.strictObject({name:z.string().trim().min(1).max(120)})).max(100)});
export type ResumeSkillExtractionInput={learnerId:string;text:string;normalizedSkills:{canonicalName:string;aliases:string[]}[]};
export interface ResumeSkillExtractor{extractResumeSkills(input:ResumeSkillExtractionInput):Promise<string[]>;}
const continuationUnit=z.strictObject({title:z.string().min(1).max(160),goal:z.string().min(1).max(500),conceptNames:z.array(z.string().min(1).max(120)).min(1).max(20),prerequisites:z.array(z.string().min(1).max(120)).max(20),productContext:z.string().min(1).max(500),futureLabOutcome:z.string().min(1).max(500)});
export const continuationPlanSchema=z.strictObject({remainingRequirements:z.array(z.string()).max(100),remainingCapabilityGaps:z.array(z.string()).max(100),prerequisiteDependencies:z.array(z.string()).max(100),noTeachingNeeded:z.array(z.string()).max(100),repairConcepts:z.array(z.string()).max(100),mergeIntoFutureLabs:z.array(z.string()).max(100),plannedUnits:z.number().int().min(1).max(20),plannedLabs:z.number().int().min(0).max(20),proposedUnits:z.array(continuationUnit).min(1).max(20)}).refine(x=>x.proposedUnits.length===x.plannedUnits,"One outline is required per planned unit");
export type ContinuationPlan=z.infer<typeof continuationPlanSchema>;
export type ContinuationReasoningInput={learnerId:string;goal:string;targetPath:string|null;context:unknown;selectedScope:unknown;completedUnits:unknown;labEvidence:unknown;markers:unknown;doubts:unknown;conceptState:unknown;timelineDays:number|null;pace:string|null};
export type ReasoningFailureCategory="PROVIDER_TIMEOUT"|"NETWORK_FAILURE"|"AUTHENTICATION_FAILURE"|"INVALID_MODEL"|"RATE_LIMIT"|"OPENAI_5XX"|"OPENAI_HTTP_ERROR"|"INCOMPLETE_RESPONSE"|"REFUSED_RESPONSE"|"EMPTY_OUTPUT"|"JSON_PARSE_FAILURE"|"SCHEMA_VALIDATION_FAILURE"|"RETRY_EXHAUSTED";
export class ReasoningProviderError extends Error{
  constructor(readonly category:ReasoningFailureCategory,message:string,readonly details:{stage:string;status?:number;code?:string;retryable:boolean;attempt:number;causeCategory?:ReasoningFailureCategory;validationIssues?:{path:string;code:string}[]}){super(message);this.name="ReasoningProviderError";}
}
type ReasoningLog=(level:"info"|"warn"|"error",event:Record<string,unknown>)=>void;
type ProviderOptions={timeoutMs?:number;maxRetries?:number;fetchImpl?:typeof fetch;sleep?:(ms:number)=>Promise<void>;log?:ReasoningLog};
export const generatedLabSchema=z.strictObject({overview:z.string().min(1).max(3000),goal:z.string().min(1).max(1000),evaluationCriteria:z.array(z.string().min(1).max(500)).min(1).max(20),files:z.array(z.strictObject({path:z.string().min(1).max(300),role:z.enum(["PROVIDED","READ_ONLY","YOU_BUILD","OPTIONAL_REFERENCE","TEST"]),content:z.string().max(100000),humanMeaning:z.string().min(1).max(1000),technicalRole:z.string().min(1).max(1000),inputOutput:z.string().min(1).max(1000),learningPurpose:z.string().min(1).max(1000)})).min(1).max(30)})
  .refine(x=>x.files.some(f=>f.role==="YOU_BUILD"),"A generated lab needs learner-owned work")
  .refine(x=>x.files.filter(f=>f.role==="YOU_BUILD").every(f=>f.content.trim().length>0),"Every YOU_BUILD file needs editable starter code");
export type GeneratedLab=z.infer<typeof generatedLabSchema>;
const teachingBlock=z.strictObject({
  type:z.enum(["TEXT","BULLETS","CODE","CHECKPOINT"]),title:z.string().min(1).max(120),
  body:z.string().max(1000),items:z.array(z.string().min(1).max(240)).max(4),
  language:z.string().max(40),code:z.string().max(3000),
}).superRefine((block,ctx)=>{
  if(block.type==="CODE"){
    if(!block.code.trim()||!block.language.trim()||block.code.split(/\r?\n/).length>25||block.code.includes("```"))
      ctx.addIssue({code:"custom",message:"CODE requires a language and unfenced code of at most 25 lines"});
  }else if(block.code||block.language||(!block.body.trim()&&!block.items.length)){
    ctx.addIssue({code:"custom",message:"Non-code blocks require teaching text or bullets and empty code/language"});
  }
  if(block.body.includes("```"))ctx.addIssue({code:"custom",message:"Use a structured CODE block instead of fenced prose"});
});
const conceptLesson=z.strictObject({conceptKey:key,title:z.string().min(1).max(160),objective:z.string().min(1).max(300),blocks:z.array(teachingBlock).min(4).max(6),recap:z.array(z.string().min(1).max(240)).min(2).max(4)})
  .refine(lesson=>lesson.blocks.filter(block=>block.type==="CODE").length<=1,"Use at most one focused code example per concept");
export const generatedUnitTeachingSchema=z.strictObject({introduction:z.string().min(1).max(400),lessons:z.array(conceptLesson).min(1).max(8)});
export type GeneratedUnitTeaching=z.infer<typeof generatedUnitTeachingSchema>;
export interface LearningReasoningProvider extends ResumeSkillExtractor{readonly provider:string;readonly model:string;propose(input:LearnerReasoningInput):Promise<{responseId:string;value:Proposal}>;generateUnits(input:ConfirmedScopeInput):Promise<{responseId:string;value:UnitsPlan}>;generateUnitTeaching?(input:{learnerId:string;targetDepth:"BASIC"|"STANDARD"|"DEEP";unit:unknown;concepts:unknown;learnerContext:unknown;knownConcepts:unknown}):Promise<{responseId:string;value:GeneratedUnitTeaching}>;generateDoubtClarification?(input:{learnerId:string;doubt:unknown;unit:unknown;labEvidence:unknown}):Promise<{responseId:string;value:{explanation:string;recap:string[]}}>;analyzeContinuation?(input:ContinuationReasoningInput):Promise<{responseId:string;value:ContinuationPlan}>;generateLab?(input:{learnerId:string;unit:unknown;learnerContext:unknown;knownConcepts:unknown;doubts:unknown;assistanceHistory:unknown;repairNeeds:unknown}):Promise<{responseId:string;value:GeneratedLab}>;generateLabHint?(input:{learnerId:string;lab:unknown;file:{fileId:string;path:string;content:string};attempt:unknown;hintNumber:1|2;previousHints:string[]}):Promise<{responseId:string;text:string}>;generateGlossaryMeaning?(input:{learnerId:string;selectedText:string;sourceContext:string|null}):Promise<{responseId:string;simpleMeaning:string;technicalMeaning:string}>;generateSystemAssistance?(input:{learnerId:string;lab:unknown;files:unknown;previousHints:string[]}):Promise<{responseId:string;content:string}>;}

const keyJsonSchema={type:"string",pattern:"^[a-z0-9][a-z0-9-]{1,79}$"};
const proposalJsonSchema={type:"object",additionalProperties:false,required:["targetPath","requirements","capabilities"],properties:{
  targetPath:{type:"string",enum:["FRONTEND_ENGINEER","BACKEND_ENGINEER","FULL_STACK_ENGINEER","AI_APPLICATION_ENGINEER","CLOUD_DEVOPS_ENGINEER"]},
  requirements:{type:"array",minItems:1,maxItems:30,items:{type:"object",additionalProperties:false,required:["name","classification","reason","source"],properties:{name:{type:"string"},classification:{type:"string",enum:["REQUIRED","USEFUL","OPTIONAL"]},reason:{type:"string"},source:{type:"string",enum:["GOAL","PROFILE","JD","INTEREST"]}}}},
  capabilities:{type:"array",minItems:2,maxItems:6,items:{type:"object",additionalProperties:false,required:["key","name","tab","reason","scenario","concepts"],properties:{key:keyJsonSchema,name:{type:"string"},tab:{type:"string"},reason:{type:"string"},scenario:{type:"string"},concepts:{type:"array",minItems:1,maxItems:20,items:{type:"object",additionalProperties:false,required:["key","name","shortExample","relationship","recommendationReason","selected","depthCategory","requirementClass","aliases","prerequisites"],properties:{key:keyJsonSchema,name:{type:"string"},shortExample:{type:"string"},relationship:{type:"string",enum:["KNOWN_REPORTED","RECOMMENDED_NEXT","DEEPER_OPTIONAL","NOT_RELEVANT"]},recommendationReason:{type:"string",minLength:12,maxLength:500},selected:{type:"boolean"},depthCategory:{type:"string",enum:["FOUNDATION","APPLIED","DEEP"]},requirementClass:{type:"string",enum:["REQUIRED","USEFUL","OPTIONAL"]},aliases:{type:"array",maxItems:15,items:{type:"string"}},prerequisites:{type:"array",maxItems:15,items:keyJsonSchema}}}}}}}
}};
const unitsJsonSchema={type:"object",additionalProperties:false,required:["units"],properties:{units:{type:"array",minItems:2,maxItems:2,items:{type:"object",additionalProperties:false,required:["sequence","title","goal","conceptKeys","prerequisiteNames","productContext","groupingReason","futureLabOutcome"],properties:{sequence:{type:"integer",enum:[1,2]},title:{type:"string"},goal:{type:"string"},conceptKeys:{type:"array",minItems:1,items:keyJsonSchema},prerequisiteNames:{type:"array",items:{type:"string"}},productContext:{type:"string"},groupingReason:{type:"string"},futureLabOutcome:{type:"string"}}}}}};
const continuationJsonSchema={type:"object",additionalProperties:false,required:["remainingRequirements","remainingCapabilityGaps","prerequisiteDependencies","noTeachingNeeded","repairConcepts","mergeIntoFutureLabs","plannedUnits","plannedLabs","proposedUnits"],properties:{remainingRequirements:{type:"array",items:{type:"string"}},remainingCapabilityGaps:{type:"array",items:{type:"string"}},prerequisiteDependencies:{type:"array",items:{type:"string"}},noTeachingNeeded:{type:"array",items:{type:"string"}},repairConcepts:{type:"array",items:{type:"string"}},mergeIntoFutureLabs:{type:"array",items:{type:"string"}},plannedUnits:{type:"integer",minimum:1,maximum:20},plannedLabs:{type:"integer",minimum:0,maximum:20},proposedUnits:{type:"array",minItems:1,maxItems:20,items:{type:"object",additionalProperties:false,required:["title","goal","conceptNames","prerequisites","productContext","futureLabOutcome"],properties:{title:{type:"string"},goal:{type:"string"},conceptNames:{type:"array",minItems:1,items:{type:"string"}},prerequisites:{type:"array",items:{type:"string"}},productContext:{type:"string"},futureLabOutcome:{type:"string"}}}}}};
// Derive the provider contract from the same size limits used before persistence.
// Cross-field refinements are additionally checked locally after the response.
const teachingJsonSchema=z.toJSONSchema(generatedUnitTeachingSchema,{unrepresentable:"any"});
const clarificationJsonSchema={type:"object",additionalProperties:false,required:["explanation","recap"],properties:{explanation:{type:"string"},recap:{type:"array",minItems:1,maxItems:6,items:{type:"string"}}}};

export class OpenAILearningReasoningProvider implements LearningReasoningProvider{
  readonly provider="OPENAI";
  readonly timeoutMs:number;readonly maxRetries:number;
  private readonly fetchImpl:typeof fetch;private readonly sleep:(ms:number)=>Promise<void>;private readonly log:ReasoningLog;
  constructor(private readonly apiKey:string,readonly model:string,options:ProviderOptions={}){
    this.timeoutMs=options.timeoutMs??90_000;this.maxRetries=options.maxRetries??1;this.fetchImpl=options.fetchImpl??fetch;
    this.sleep=options.sleep??(ms=>new Promise(resolve=>setTimeout(resolve,ms)));this.log=options.log??(()=>{});
  }
  private failure(category:ReasoningFailureCategory,stage:string,attempt:number,retryable:boolean,status?:number,code?:string){
    return new ReasoningProviderError(category,category,{stage,attempt,retryable,...(status===undefined?{}:{status}),...(code?{code}:{})});
  }
  private async request<T>(learnerId:string,name:string,schema:object,instructions:string,input:unknown,parse:(value:unknown)=>T){
    const started=Date.now();const serializedInput=JSON.stringify(input);let last:ReasoningProviderError|undefined;
    for(let attempt=1;attempt<=this.maxRetries+1;attempt++){
      const attemptStarted=Date.now();this.log("info",{stage:"request_started",model:this.model,operation:name,attempt,maxAttempts:this.maxRetries+1,timeoutMs:this.timeoutMs,inputBytes:Buffer.byteLength(serializedInput),instructionBytes:Buffer.byteLength(instructions)});
      try{
        const response=await this.fetchImpl("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${this.apiKey}`,"content-type":"application/json"},signal:AbortSignal.timeout(this.timeoutMs),body:JSON.stringify({model:this.model,store:false,reasoning:{effort:name==="adaptive_learning_scope"?"low":"medium"},instructions,input:serializedInput,text:{format:{type:"json_schema",name,strict:true,schema}},safety_identifier:createHash("sha256").update(learnerId).digest("hex").slice(0,64)})});
        let body:{id?:string;status?:string;output?:{type?:string;content?:{type?:string;text?:string;refusal?:string}[]}[];error?:{code?:string;type?:string;message?:string};incomplete_details?:{reason?:string}};
        try{body=await response.json() as typeof body;}catch{throw this.failure("JSON_PARSE_FAILURE","provider_response_json",attempt,false,response.status);}
        const providerCode=body.error?.code??body.error?.type;
        if(!response.ok){
          const category=response.status===401||response.status===403?"AUTHENTICATION_FAILURE":response.status===404||providerCode==="model_not_found"?"INVALID_MODEL":response.status===429?"RATE_LIMIT":response.status>=500?"OPENAI_5XX":"OPENAI_HTTP_ERROR";
          throw this.failure(category,"provider_http",attempt,category==="RATE_LIMIT"||category==="OPENAI_5XX"||response.status===408,response.status,providerCode);
        }
        const refusal=body.output?.flatMap(x=>x.content??[]).find(x=>x.type==="refusal");
        if(refusal)throw this.failure("REFUSED_RESPONSE","provider_output",attempt,false,response.status);
        if(body.status!=="completed")throw this.failure("INCOMPLETE_RESPONSE","provider_output",attempt,false,response.status,body.incomplete_details?.reason);
        const text=body.output?.flatMap(x=>x.content??[]).find(x=>x.type==="output_text")?.text;
        if(!text||!body.id)throw this.failure("EMPTY_OUTPUT","provider_output",attempt,false,response.status);
        let decoded:unknown;try{decoded=JSON.parse(text);}catch{throw this.failure("JSON_PARSE_FAILURE","structured_output_json",attempt,false,response.status);}
        let value:T;try{value=parse(decoded);}catch(error){
          const failure=this.failure("SCHEMA_VALIDATION_FAILURE","structured_output_validation",attempt,false,response.status,error instanceof z.ZodError?"ZOD_VALIDATION_FAILED":undefined);
          if(error instanceof z.ZodError)failure.details.validationIssues=error.issues.slice(0,20).map(issue=>({path:issue.path.join("."),code:issue.code==="custom"&&typeof issue.params?.reason==="string"?issue.params.reason:issue.code}));
          throw failure;
        }
        this.log("info",{stage:"structured_output_validated",model:this.model,operation:name,attempt,elapsedMs:Date.now()-attemptStarted,totalElapsedMs:Date.now()-started,validationSucceeded:true});
        return {responseId:body.id,value};
      }catch(error){
        const classified=error instanceof ReasoningProviderError?error:error instanceof DOMException&&["AbortError","TimeoutError"].includes(error.name)?this.failure("PROVIDER_TIMEOUT","provider_request",attempt,true):this.failure("NETWORK_FAILURE","provider_request",attempt,true,undefined,error instanceof Error?error.name:undefined);
        last=classified;const willRetry=classified.details.retryable&&attempt<=this.maxRetries;
        this.log(willRetry?"warn":"error",{stage:classified.details.stage,model:this.model,operation:name,attempt,elapsedMs:Date.now()-attemptStarted,totalElapsedMs:Date.now()-started,category:classified.category,status:classified.details.status,errorCode:classified.details.code,timeoutCategory:classified.category==="PROVIDER_TIMEOUT"?"provider_request_timeout":null,structuredOutputValidated:false,validationIssues:classified.details.validationIssues,willRetry});
        if(!willRetry){
          if(classified.details.retryable&&attempt>this.maxRetries)throw new ReasoningProviderError("RETRY_EXHAUSTED","RETRY_EXHAUSTED",{stage:"retry_exhausted",attempt,retryable:false,causeCategory:classified.category,...(classified.details.status===undefined?{}:{status:classified.details.status}),...(classified.details.code?{code:classified.details.code}:{})});
          throw classified;
        }
        await this.sleep(500*2**(attempt-1));
      }
    }
    throw last??this.failure("RETRY_EXHAUSTED","retry_exhausted",this.maxRetries+1,false);
  }
  propose(input:LearnerReasoningInput){return this.request(input.learnerId,"adaptive_learning_scope",proposalJsonSchema,
    "You are the AdaptiveSkills curriculum reasoning engine. Support only Frontend Engineer, Backend Engineer, Full-Stack Engineer, AI Application Engineer, or Cloud/DevOps Engineer. Dynamically infer the best target path from the learner goal. Plan the FULL LEARNING SCOPE, not merely the first two units. targetDepth BASIC, STANDARD, or DEEP controls eventual breadth, concept granularity, dependency depth, expected responsibility, and practical complexity. Build 2 to 6 capabilities with up to 20 concepts each when needed; do not compress the full scope into a trial. Treat self-reported and CV skills only as KNOWN_REPORTED, never proven. Known concepts stay visible and unselected. Every recommendationReason must be meaningful and contextual. Use lowercase kebab-case keys. Every prerequisite must reference another concept in this response. Normalize terminology when possible, but allow unmapped concepts. Do not generate lessons or labs.",input,value=>proposalSchema.parse(value));}
  generateUnits(input:ConfirmedScopeInput){return this.request(input.learnerId,"adaptive_trial_units",unitsJsonSchema,
    "Organize the supplied CURRENT RUNWAY SLICE into exactly two coherent trial learning-unit definitions. Use every supplied runway concept exactly once, with at most three concepts per unit. The learner's wider confirmed scope is intentionally not supplied here. Respect prerequisites and put foundations before dependent work. Personalize titles, goals, product context, and a future lab outcome. Define unit outlines only.",input,value=>unitsPlanSchema.parse(value));}
  generateUnitTeaching(input:{learnerId:string;targetDepth:"BASIC"|"STANDARD"|"DEEP";unit:unknown;concepts:unknown;learnerContext:unknown;knownConcepts:unknown}){return this.request(input.learnerId,"adaptive_unit_teaching",teachingJsonSchema,
    "Generate compact mobile-first teaching for this already-planned unit, exactly one ordered lesson per supplied concept key and no others. Teach actual material, not a syllabus or textbook chapter. Use 4-6 short blocks: a plain explanation, why it matters in this learner's context, key technical patterns, one compact worked example, and a short checkpoint where useful; finish with 2-4 recap bullets. Prefer TEXT, BULLETS, CODE, CHECKPOINT. Keep paragraphs short and avoid repeating the unit introduction. Preserve technical correctness and targetDepth: BASIC explains foundations; STANDARD teaches applied choices; DEEP adds precise tradeoffs, failure modes and practical responsibility within the same compact format, not extra concepts. Use one focused code example only when code helps teach this concept; prefer 8-20 lines, never over 25. No full application, bootstrap, installation boilerplate or multiple implementations. Include only a few useful WHY comments for non-obvious decisions, never comments narrating obvious lines. CODE blocks must use language and code fields with preserved indentation and newlines, never Markdown fences. For CODE, body is an optional short caption and items are optional what-to-notice bullets. For other blocks code and language must be empty strings. A non-code worked example is valid where more appropriate. Body maximum 1000 characters, at most 4 bullets of 240 characters each, introduction maximum 400 characters. Use learner context without quoting private JD/profile text. Do not generate labs, hints, pricing or unrelated concepts.",input,value=>generatedUnitTeachingSchema.parse(value));}
  generateDoubtClarification(input:{learnerId:string;doubt:unknown;unit:unknown;labEvidence:unknown}){return this.request(input.learnerId,"adaptive_doubt_clarification",clarificationJsonSchema,"Clarify this learner's unresolved theory doubt after their lab. Give a focused explanation tied to the unit and observed lab evidence, followed by a short recap. Do not invent completion evidence or introduce an unrelated curriculum.",input,value=>{const parsed=z.strictObject({explanation:z.string().min(1).max(5000),recap:z.array(z.string().min(1).max(500)).min(1).max(6)}).parse(value);return parsed;});}
  analyzeContinuation(input:ContinuationReasoningInput){return this.request(input.learnerId,"adaptive_continuation_plan",continuationJsonSchema,
    "Analyze what remains after a completed paid learning runway. Use the learner goal, evidence, assistance, doubts, markers, dependencies and timeline. Do not choose prices or commercial tiers. Do not generate full lessons or labs. Propose a bounded next runway using unit outlines only. Avoid reteaching proven concepts; identify repair and concepts that can be merged into future labs.",input,value=>continuationPlanSchema.parse(value));}
  generateLab(input:{learnerId:string;unit:unknown;learnerContext:unknown;knownConcepts:unknown;doubts:unknown;assistanceHistory:unknown;repairNeeds:unknown}){const file={type:"object",additionalProperties:false,required:["path","role","content","humanMeaning","technicalRole","inputOutput","learningPurpose"],properties:{path:{type:"string"},role:{type:"string",enum:["PROVIDED","READ_ONLY","YOU_BUILD","OPTIONAL_REFERENCE","TEST"]},content:{type:"string"},humanMeaning:{type:"string"},technicalRole:{type:"string"},inputOutput:{type:"string"},learningPurpose:{type:"string"}}};const schema={type:"object",additionalProperties:false,required:["overview","goal","evaluationCriteria","files"],properties:{overview:{type:"string"},goal:{type:"string"},evaluationCriteria:{type:"array",minItems:1,items:{type:"string"}},files:{type:"array",minItems:1,items:file}}};return this.request(input.learnerId,"adaptive_generated_lab",schema,"Generate a focused practical lab for this learning unit. Incorporate relevant unresolved doubts naturally and preserve prerequisites. Every YOU_BUILD file must contain useful, editable starter code or a scaffold with the imports, types, function signatures and context needed to begin; never return an empty YOU_BUILD file. Leave meaningful implementation work for the learner and do not provide the complete solution. Provide files outside the learner's responsibility as PROVIDED, READ_ONLY, OPTIONAL_REFERENCE or TEST. Include tests and clear evaluation criteria. Keep the core domain generic even when this instance is technical.",input,value=>generatedLabSchema.parse(value));}
  async generateLabHint(input:{learnerId:string;lab:unknown;file:{fileId:string;path:string;content:string};attempt:unknown;hintNumber:1|2;previousHints:string[]}){const schema={type:"object",additionalProperties:false,required:["text"],properties:{text:{type:"string"}}};const result=await this.request(input.learnerId,"adaptive_lab_hint",schema,input.hintNumber===1?"Give concise directional guidance only for the selected learner-owned file and its current saved draft. Point to the next useful change without revealing the implementation. Do not give a whole-lab hint or discuss unrelated files.":"Give a stronger, concise scaffold only for the selected learner-owned file and its current saved draft. Leave meaningful learner work. This is the final hint; do not invent another hint or give a whole-lab solution.",input,value=>z.strictObject({text:z.string().min(1).max(2000)}).parse(value));return{responseId:result.responseId,text:result.value.text};}
  async generateGlossaryMeaning(input:{learnerId:string;selectedText:string;sourceContext:string|null}){const schema={type:"object",additionalProperties:false,required:["simpleMeaning","technicalMeaning"],properties:{simpleMeaning:{type:"string"},technicalMeaning:{type:"string"}}};const result=await this.request(input.learnerId,"adaptive_glossary_meaning",schema,"Explain the selected term from its learning context. Give a short plain-language meaning and a precise technical meaning. Do not invent learner facts.",input,value=>z.strictObject({simpleMeaning:z.string().min(1).max(1000),technicalMeaning:z.string().min(1).max(2000)}).parse(value));return{responseId:result.responseId,...result.value};}
  async generateSystemAssistance(input:{learnerId:string;lab:unknown;files:unknown;previousHints:string[]}){const schema={type:"object",additionalProperties:false,required:["content"],properties:{content:{type:"string"}}};const result=await this.request(input.learnerId,"adaptive_system_assistance",schema,"The learner explicitly requested system assistance after using both allowed hints. Explain the missing reasoning and provide or reveal the remaining implementation needed to proceed. This is system assistance, not another hint, and must not be described as independent learner work.",input,value=>z.strictObject({content:z.string().min(1).max(20000)}).parse(value));return{responseId:result.responseId,content:result.value.content};}
  async extractResumeSkills(input:ResumeSkillExtractionInput){
    const result=await this.request(input.learnerId,"adaptive_resume_skills",{type:"object",additionalProperties:false,required:["skills"],properties:{skills:{type:"array",maxItems:100,items:{type:"object",additionalProperties:false,required:["name"],properties:{name:{type:"string"}}}}}},
      "Extract explicit professional, technical, domain, tool, platform, language, and transferable skills supported by the resume text. Return concise skill names only. Do not infer unsupported skills. The supplied normalized vocabulary is terminology guidance, not an allowlist: preserve useful skills that are absent from it. Do not return personal details, employers, schools, job titles, or prose.",input,value=>resumeSkillsSchema.parse(value));
    return result.value.skills.map(skill=>skill.name);
  }
}

